name: Leandro Simões
bio: 'Software Developer, Professor e Mestre em Ciência da Computação'
description: Um blog com várias coisas
external-image: false
picture: assets/images/leprofile.jpg
resume: false
resume-external: false
# url: 'https://koppl.in/indigo'
permalink: '/:title/'
disqus:
  shortname: lesimoes
  categories:
    - blog
    - project
linkedin: leandro-sim%C3%B5es-msc-98993428/
spotify: 12161425370?si=_-fV0VbrTvm2j3Lcto3-xg
github: lesimoes
email: lesimoes0@gmail.com
lattes: 0520168580624517
authors:
  lesimoes:
    name: Le
    bio: 'Software Developer, Professor e Mestre em Ciência da Computação'
    external-image: false
    picture: assets/images/leprofile.jpg
width: normal
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
